# Generated by Django 4.0.3 on 2022-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_part', models.CharField(max_length=100)),
                ('artile_number', models.IntegerField(max_length=10)),
                ('name_of_car', models.CharField(max_length=50)),
                ('descrition', models.TextField()),
                ('part_number', models.IntegerField(default=None)),
                ('photo', models.BooleanField(default=None)),
                ('price', models.IntegerField(max_length=10)),
                ('discount', models.IntegerField(max_length=2)),
                ('active_status', models.BooleanField(default=None)),
                ('sold_status', models.BooleanField(default=None)),
            ],
        ),
    ]
