# Generated by Django 4.0.3 on 2022-04-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparepart',
            old_name='descrition',
            new_name='description',
        ),
    ]
