# Generated by Django 4.0.3 on 2022-04-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0002_rename_descrition_sparepart_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='artile_number',
        ),
    ]
