# Generated by Django 4.0.3 on 2022-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_remove_sparepart_artile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='sold_status',
            field=models.BooleanField(default=False),
        ),
    ]
