# Generated by Django 4.0.3 on 2022-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0004_alter_sparepart_sold_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
