# Generated by Django 4.0.3 on 2022-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0005_alter_sparepart_active_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('name_of_part', models.CharField(max_length=20)),
                ('model_of_auto', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='SparePart',
        ),
    ]
