# Generated by Django 4.0.3 on 2022-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_remove_category_model_of_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sparepartsubcategory',
            name='name_of_part',
            field=models.TextField(max_length=20),
        ),
    ]
