# Generated by Django 4.0.3 on 2022-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0008_alter_sparepart_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partimage',
            name='image',
            field=models.ImageField(default='test.jpg', upload_to='profile_pics'),
        ),
    ]
